import OracleDB from "oracledb";
import { users } from "../setup/users.js";

// Connection Pool Configuration
const ifcPoolConfig = {
  user: "ifcAdmin",
  password: "123456",
  connectString: "localhost:1521/ORCLPDB",
  poolAlias: 'ifcPool',
  poolMax: 10,
  poolMin: 2,
  poolIncrement: 1,
};

const mrimsPoolConfig = {
  user: "mrims",
  password: "123456",
  connectString: "localhost:1521/ORCLPDB",
  poolAlias: 'mrimsPool',
  poolMax: 10,
  poolMin: 2,
  poolIncrement: 1,
};

export let ifcPool: OracleDB.Pool | undefined;
export let mrimsPool: OracleDB.Pool | undefined;

// ✅ Connection Pool 생성
export async function initPools() {
  try {
    ifcPool = await OracleDB.createPool(ifcPoolConfig);
    console.log("✅ IFC Connection Pool 생성 완료");
    mrimsPool = await OracleDB.createPool(mrimsPoolConfig);
    console.log("✅ MRIMS Connection Pool 생성 완료");

    // DB Schema 확인 및 자동 생성/마이그레이션 실행
    await verifySchema();

    // 애플리케이션 종료 시 Connection Pool 종료
    process.on("SIGTERM", closeDatabase);
    process.on("SIGINT", closeDatabase);
  } catch (err) {
    console.error("❌ Connection Pool 생성 실패:", err);
    throw err;
  }
}

// ✅ Oracle DB 스키마 확인 및 마이그레이션 자동 실행
async function verifySchema() {
  let connection: OracleDB.Connection | undefined;
  try {
    connection = await getConnection();

    // 1. user 테이블 확인 및 생성
    let tableExists = await checkTableExists(connection, "user");
    if (!tableExists) {
      console.log("🛠️ 'user' 테이블 생성 중...");
      await connection.execute(`
        CREATE TABLE "user" (
          "email" VARCHAR2(255) PRIMARY KEY,
          "name" VARCHAR2(255) NOT NULL,
          "picture" VARCHAR2(255),
          "security" VARCHAR2(50) NOT NULL
        )
      `);
      console.log("✅ 'user' 테이블 생성 완료.");
    }

    // 2. project 테이블 확인 및 생성
    tableExists = await checkTableExists(connection, "project");
    if (!tableExists) {
      console.log("🛠️ 'project' 테이블 생성 중...");
      await connection.execute(`
        CREATE TABLE "project" (
          "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "name" VARCHAR2(255) NOT NULL,
          "description" VARCHAR2(1000)
        )
      `);
      console.log("✅ 'project' 테이블 생성 완료.");
    }

    // 3. project_user 테이블 확인 및 생성
    tableExists = await checkTableExists(connection, "project_user");
    if (!tableExists) {
      console.log("🛠️ 'project_user' 테이블 생성 중...");
      await connection.execute(`
        CREATE TABLE "project_user" (
          "project_id" NUMBER NOT NULL,
          "user_email" VARCHAR2(255) NOT NULL,
          "security" VARCHAR2(50) NOT NULL,
          CONSTRAINT "pk_project_user" PRIMARY KEY ("project_id", "user_email"),
          CONSTRAINT "fk_project_user_project" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE,
          CONSTRAINT "fk_project_user_user" FOREIGN KEY ("user_email") REFERENCES "user"("email") ON DELETE CASCADE
        )
      `);
      console.log("✅ 'project_user' 테이블 생성 완료.");
    }

    // 4. ifc 테이블에 project_id 컬럼 추가 및 외래키 설정
    const ifcColExists = await checkColumnExists(connection, "ifc", "project_id");
    if (!ifcColExists) {
      console.log("🛠️ 'ifc' 테이블에 'project_id' 컬럼 추가 중...");
      await connection.execute(`ALTER TABLE "ifc" ADD "project_id" NUMBER NULL`);
      try {
        await connection.execute(`
          ALTER TABLE "ifc" ADD CONSTRAINT "fk_ifc_project" 
          FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE SET NULL
        `);
      } catch (err) {
        console.error("Constraint fk_ifc_project might already exist:", err);
      }
      console.log("✅ 'ifc' 테이블 마이그레이션 완료.");
    }

    // 5. frag 테이블에 project_id 컬럼 추가 및 외래키 설정
    const fragColExists = await checkColumnExists(connection, "frag", "project_id");
    if (!fragColExists) {
      console.log("🛠️ 'frag' 테이블에 'project_id' 컬럼 추가 중...");
      await connection.execute(`ALTER TABLE "frag" ADD "project_id" NUMBER NULL`);
      try {
        await connection.execute(`
          ALTER TABLE "frag" ADD CONSTRAINT "fk_frag_project" 
          FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE SET NULL
        `);
      } catch (err) {
        console.error("Constraint fk_frag_project might already exist:", err);
      }
      console.log("✅ 'frag' 테이블 마이그레이션 완료.");
    }

    // 6. DB 내의 예전 사용자 중 users.ts 에 존재하지 않는 사용자 삭제 (Cascade Option으로 project_user 자동 정리)
    const dbUsersResult = await connection.execute(
      `SELECT "email" FROM "user"`,
      [],
      { outFormat: OracleDB.OUT_FORMAT_OBJECT }
    );
    if (dbUsersResult.rows) {
      for (const row of dbUsersResult.rows as any[]) {
        const dbEmail = row.email ?? row.EMAIL;
        if (dbEmail && !users[dbEmail]) {
          console.log(`🗑️ DB에서 사용되지 않는 사용자 제거: ${dbEmail}`);
          await connection.execute(`DELETE FROM "user" WHERE "email" = :email`, { email: dbEmail });
        }
      }
    }

    // 7. 신규 사용자 추가 및 기존 사용자 정보 동기화 (src/setup/users.ts 연동)
    for (const email of Object.keys(users)) {
      const user = users[email];
      const result = await connection.execute(
        `SELECT COUNT(*) AS CNT FROM "user" WHERE "email" = :email`,
        { email },
        { outFormat: OracleDB.OUT_FORMAT_OBJECT }
      );
      const cnt = (result.rows?.[0] as any)?.CNT ?? (result.rows?.[0] as any)?.cnt ?? 0;
      if (cnt === 0) {
        console.log(`👤 사용자 추가: ${email}`);
        await connection.execute(
          `INSERT INTO "user" ("email", "name", "picture", "security") VALUES (:email, :name, :picture, :security)`,
          {
            email,
            name: user.name,
            picture: user.picture || null,
            security: user.security
          }
        );
      } else {
        console.log(`👤 사용자 정보 동기화: ${email}`);
        await connection.execute(
          `UPDATE "user" SET "name" = :name, "picture" = :picture, "security" = :security WHERE "email" = :email`,
          {
            email,
            name: user.name,
            picture: user.picture || null,
            security: user.security
          }
        );
      }
    }
    await connection.commit();

    // 8. 프로젝트별 권한 매핑 보장
    const allProjectsResult = await connection.execute(
      `SELECT "id" FROM "project"`,
      [],
      { outFormat: OracleDB.OUT_FORMAT_OBJECT }
    );
    if (allProjectsResult.rows && allProjectsResult.rows.length > 0) {
      const freeUsersResult = await connection.execute(
        `SELECT "email" FROM "user" WHERE "security" = 'free'`,
        [],
        { outFormat: OracleDB.OUT_FORMAT_OBJECT }
      );
      const freeEmails = (freeUsersResult.rows || []).map((r: any) => r.email ?? r.EMAIL).filter(Boolean);
      if (freeEmails.length > 0) {
        for (const projRow of allProjectsResult.rows as any[]) {
          const projId = projRow.id ?? projRow.ID;
          const linkedFreeUsersCountResult = await connection.execute(
            `SELECT COUNT(*) AS CNT 
             FROM "project_user" pu 
             JOIN "user" u ON pu."user_email" = u."email" 
             WHERE pu."project_id" = :project_id AND u."security" = 'free'`,
            { project_id: projId },
            { outFormat: OracleDB.OUT_FORMAT_OBJECT }
          );
          const cnt = (linkedFreeUsersCountResult.rows?.[0] as any)?.CNT ?? (linkedFreeUsersCountResult.rows?.[0] as any)?.cnt ?? 0;
          if (cnt === 0) {
            console.log(`🛠️ 프로젝트 ID ${projId}에 연결된 free 사용자가 없어 자동 연결합니다.`);
            for (const freeEmail of freeEmails) {
              await connection.execute(
                `MERGE INTO "project_user" dest
                 USING (SELECT :project_id AS "project_id", :user_email AS "user_email", 'free' AS "security" FROM DUAL) src
                 ON (dest."project_id" = src."project_id" AND dest."user_email" = src."user_email")
                 WHEN MATCHED THEN
                   UPDATE SET dest."security" = 'free'
                 WHEN NOT MATCHED THEN
                   INSERT ("project_id", "user_email", "security")
                   VALUES (src."project_id", src."user_email", src."security")`,
                {
                  project_id: projId,
                  user_email: freeEmail
                }
              );
            }
          }
        }
      }
    }

    // 기존 DB 내에 업로드되어 있던 IFC/FRAG 모델이 있다면 첫 번째 시드 프로젝트에 매핑하여 유지
    const firstProjectResult = await connection.execute(
      `SELECT "id" FROM "project" ORDER BY "id" ASC`,
      [],
      { outFormat: OracleDB.OUT_FORMAT_OBJECT }
    );
    if (firstProjectResult.rows && firstProjectResult.rows.length > 0) {
      const firstId = (firstProjectResult.rows[0] as any).id ?? (firstProjectResult.rows[0] as any).ID;
      if (firstId) {
        await connection.execute(`UPDATE "ifc" SET "project_id" = :projId WHERE "project_id" IS NULL`, { projId: firstId });
        await connection.execute(`UPDATE "frag" SET "project_id" = :projId WHERE "project_id" IS NULL`, { projId: firstId });
        console.log(`🔗 기존 고아 모델들을 첫 번째 프로젝트(ID: ${firstId})에 연결했습니다.`);
      }
    }

    await connection.commit();
    console.log("✅ 기본 프로젝트 및 매핑 검증 완료.");
  } catch (err) {
    if (connection) {
      await connection.rollback();
    }
    console.error("❌ DB 스키마 검증 및 마이그레이션 실패:", err);
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (closeErr) {
        console.error("verifySchema close connection error:", closeErr);
      }
    }
  }
}

async function checkTableExists(connection: OracleDB.Connection, tableName: string): Promise<boolean> {
  try {
    const result = await connection.execute(
      `SELECT table_name FROM user_tables WHERE UPPER(table_name) = UPPER(:table_name)`,
      { table_name: tableName }
    );
    return !!(result.rows && result.rows.length > 0);
  } catch (e) {
    return false;
  }
}

async function checkColumnExists(connection: OracleDB.Connection, tableName: string, columnName: string): Promise<boolean> {
  try {
    const result = await connection.execute(
      `SELECT column_name FROM user_tab_cols WHERE UPPER(table_name) = UPPER(:table_name) AND UPPER(column_name) = UPPER(:column_name)`,
      { table_name: tableName, column_name: columnName }
    );
    return !!(result.rows && result.rows.length > 0);
  } catch (e) {
    return false;
  }
}

// ✅ 공통 Connection Pool 연결 함수 (IFC DB)
export async function getConnection(): Promise<OracleDB.Connection> {
  while (!ifcPool) {
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  try {
    return await ifcPool.getConnection();
  } catch (err) {
    throw new Error(`Connection failed: ${err}`);
  }
}

// ✅ 공통 Connection Pool 연결 함수 (MRIMS DB)
export async function getMrimsConnection(): Promise<OracleDB.Connection> {
  while (!mrimsPool) {
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  try {
    return await mrimsPool.getConnection();
  } catch (err) {
    throw new Error(`MRIMS Connection failed: ${err}`);
  }
}

// ✅ 공통 Connection Pool 종료 함수
export async function closePool() {
  if (ifcPool) { await ifcPool.close(10); }
  if (mrimsPool) { await mrimsPool.close(10); }
  console.log("Oracle Database connection pools closed");
}

export async function closeDatabase() {
  await closePool();
  console.log("Close Database.");
}
