----------------------
-- USER 생성 --
----------------------
CREATE USER mrims IDENTIFIED BY 123456;
DROP USER mrims CASCADE;
GRANT CONNECT, RESOURCE TO mrims;
ALTER USER mrims DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

------------------------
-- BCF TOPIC table --
------------------------
-- 테이블 생성
CREATE TABLE SI_BCF_TOPIC (
    TOPIC_NO            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,    -- 모델검토사항 번호 (Auto Increment)
    MRIMS_TYPE          VARCHAR2(50),                -- 모델검토사항 타입
    PRI_DISP            VARCHAR2(100),               -- 주관분야
    SEC_DISP            VARCHAR2(100),               -- 협조분야
    PRI_FILE            VARCHAR2(100),               -- 주관분야 파일명
    SEC_FILE            VARCHAR2(100),               -- 협조분야 파일명
    REVIEW_COMMENT      CLOB,                        -- 검토의견 (Title/Description)
    SOLVE_COMMENT       CLOB,                        -- 해결 방안에 대한 의견
    COORDX              NUMBER(20, 6),               -- 간섭위치 X 좌표
    COORDY              NUMBER(20, 6),               -- 간섭위치 Y 좌표
    COORDZ              NUMBER(20, 6),               -- 간섭위치 Z 좌표
    INSERT_DATE         DATE DEFAULT SYSDATE,        -- 검토항목 생성일자
    ISSUE_PREPARE_NAME  VARCHAR2(100),               -- 발행분야 발행자
    ISSUE_PREPARE_DATE  DATE,                        -- 발행분야 발행 일자
    RESOL_PREPARE_NAME  VARCHAR2(100),               -- 해결방안 제출자
    RESOL_PREPARE_DATE  DATE,                        -- 해결방안 제출 일자
    DUE_DATE            DATE,                        -- 검토 완료 요구일
    
    CONSTRAINT PK_SI_BCF_TOPIC PRIMARY KEY (TOPIC_NO)
);

------------------------
-- BCF COMMENT table --
------------------------
-- 테이블 생성
CREATE TABLE SI_BCF_COMMENT (
    COMMENT_NO          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY, -- 댓글 ID (Auto Increment)
    TOPIC_NO            NUMBER(10)      NOT NULL,                     -- 부모 Topic의 TOPIC_NO (FK)
    MRIMS_TYPE          VARCHAR2(50),                -- 모델검토사항 타입
    PRI_DISP            VARCHAR2(100),               -- 주관분야
    SEC_DISP            VARCHAR2(100),               -- 협조분야
    PRI_FILE            VARCHAR2(100),               -- 주관분야 파일명
    SEC_FILE            VARCHAR2(100),               -- 협조분야 파일명
    REVIEW_COMMENT      CLOB,                        -- 검토의견 (Title/Description)
    SOLVE_COMMENT       CLOB,                        -- 해결 방안에 대한 의견
    COORDX              NUMBER(20, 6),               -- 간섭위치 X 좌표
    COORDY              NUMBER(20, 6),               -- 간섭위치 Y 좌표
    COORDZ              NUMBER(20, 6),               -- 간섭위치 Z 좌표
    INSERT_DATE         DATE DEFAULT SYSDATE,        -- 검토항목 생성일자
    ISSUE_PREPARE_NAME  VARCHAR2(100),               -- 발행분야 발행자
    ISSUE_PREPARE_DATE  DATE,                        -- 발행분야 발행 일자
    RESOL_PREPARE_NAME  VARCHAR2(100),               -- 해결방안 제출자
    RESOL_PREPARE_DATE  DATE,                        -- 해결방안 제출 일자
    DUE_DATE            DATE,                        -- 검토 완료 요구일
     
    CONSTRAINT PK_SI_BCF_COMMENT PRIMARY KEY (COMMENT_NO),
    CONSTRAINT FK_SI_BCF_COMMENT_TOPIC FOREIGN KEY (TOPIC_NO) REFERENCES SI_BCF_TOPIC (TOPIC_NO) ON DELETE CASCADE
);



------------------------
-- BCF to MRIMS table --
------------------------
-- 테이블 생성
CREATE TABLE SI_BCF_TO_MRIMS (
    MRIMS_NO            NUMBER(10)      NOT NULL,    -- 모델검토사항 번호 (Auto Increment)
    MRIMS_TYPE          VARCHAR2(50),                -- 모델검토사항 타입
    PRI_DISP            VARCHAR2(100),               -- 주관분야
    SEC_DISP            VARCHAR2(100),               -- 협조분야
    PRI_FILE            VARCHAR2(100),               -- 주관분야 파일명
    SEC_FILE            VARCHAR2(100),               -- 협조분야 파일명
    REVIEW_COMMENT      CLOB,                        -- 검토의견 (Title/Description)
    SOLVE_COMMENT       CLOB,                        -- 해결 방안에 대한 의견
    COORDX              NUMBER(20, 6),               -- 간섭위치 X 좌표
    COORDY              NUMBER(20, 6),               -- 간섭위치 Y 좌표
    COORDZ              NUMBER(20, 6),               -- 간섭위치 Z 좌표
    INSERT_DATE         DATE DEFAULT SYSDATE,        -- 검토항목 생성일자
    ISSUE_PREPARE_NAME  VARCHAR2(100),               -- 발행분야 발행자
    ISSUE_PREPARE_DATE  DATE,                        -- 발행분야 발행 일자
    RESOL_PREPARE_NAME  VARCHAR2(100),               -- 해결방안 제출자
    RESOL_PREPARE_DATE  DATE,                        -- 해결방안 제출 일자
    DUE_DATE            DATE,                        -- 검토 완료 요구일
    
    CONSTRAINT PK_SI_BCF_TO_MRIMS PRIMARY KEY (MRIMS_NO)
);

----------------------
-- 모델검토사항관리 table --
-- si_mrims_tab		--
----------------------
-- 테이블 생성
CREATE TABLE SI_MRIMS_TAB (
    MRIMS_NO             VARCHAR2(13)  NOT NULL,
    MRIMS_TYPE           VARCHAR2(3),
    IOF_NAME             VARCHAR2(25),
    INT_ID               NUMBER(8),
    INT_STATUS           NUMBER(2),
    INT_TYPE             NUMBER(2),
    UNIT_NO              VARCHAR2(3),
    BLDG_NO              VARCHAR2(4),
    LEVEL_NO             VARCHAR2(3),
    C_AREA_NO            VARCHAR2(3),
    D_AREA_NO            VARCHAR2(3),
    SEQ_ID               NUMBER(5),
    PRI_DISP             VARCHAR2(3)   NOT NULL,
    SEC_DISP             VARCHAR2(3)   NOT NULL,
    PRI_FILE             VARCHAR2(25),
    SEC_FILE             VARCHAR2(25),
    PRI_TAG              VARCHAR2(30),
    SEC_TAG              VARCHAR2(30),
    REVIEW_COMMENT       VARCHAR2(1000),
    SOLVE_COMMENT        VARCHAR2(500),
    REF_COL              VARCHAR2(30),
    REF_ROW              VARCHAR2(30),
    REF_EL               VARCHAR2(30),
    COORDX               NUMBER(12,3)  NOT NULL,
    COORDY               NUMBER(12,3)  NOT NULL,
    COORDZ               NUMBER(12,3)  NOT NULL,
    MRN_NO               VARCHAR2(30),
    INSERT_DATE          DATE,
    ISSUE_PREPARE_NAME   VARCHAR2(20),
    ISSUE_PREPARE_DATE   DATE,
    ISSUE_CHECK_NAME     VARCHAR2(20),
    ISSUE_CHECK_DATE     DATE,
    RESOL_PREPARE_NAME   VARCHAR2(20),
    RESOL_PREPARE_DATE   DATE,
    RESOL_CHECK_NAME     VARCHAR2(20),
    RESOL_CHECK_DATE     DATE,
    MODEL_INCORP_NAME    VARCHAR2(10),
    MODEL_INCORP_DATE    DATE,
    DUE_DATE             DATE,
    MRIMS_STATUS         NUMBER(5)     DEFAULT 10,
    MODEL_INCORP_NAEM_R  VARCHAR2(10),
    MODEL_INCORP_DATE_R  DATE,
    PRI_FTYPE            VARCHAR2(3),
    SEC_FTYPE            VARCHAR2(3),
    MODEL_INCORP_YN      VARCHAR2(1),
    INSERT_DISP          VARCHAR2(2),
    INSERT_SABUN         VARCHAR2(20),
    MRN_STATUS           VARCHAR2(5),
    MEETING_REQUEST_YN   VARCHAR2(1),
    MEETING_REQUESTER    VARCHAR2(20),
    CONST_SCH            DATE,
    CONST_SCH_PRI        DATE,
    CONST_SCH_SEC        DATE,
    INFO_FIX_YN          VARCHAR2(10),
    DWG_FBS              VARCHAR2(10),
    DRN_NO               VARCHAR2(30),
    
    CONSTRAINT PK_SI_MRIMS_TAB PRIMARY KEY (MRIMS_NO)
);
