CREATE TABLE "ifc" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR2(255) NOT NULL,
    "content" BLOB
  );

CREATE TABLE "frag" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR2(255) NOT NULL,
    "content" BLOB
  );

CREATE TABLE "bcf" (
"id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" VARCHAR2(255) NOT NULL,
"content" BLOB,
"clash_data" CLOB
);

CREATE TABLE "ifc_bcf" (
    "ifc_id" NUMBER NOT NULL,
    "bcf_id" NUMBER NOT NULL,
    CONSTRAINT "pk_ifc_bcf" PRIMARY KEY ("ifc_id", "bcf_id"),
    CONSTRAINT "fk_ifc_bcf_ifc" FOREIGN KEY ("ifc_id") REFERENCES "ifc"("id"),
    CONSTRAINT "fk_ifc_bcf_bcf" FOREIGN KEY ("bcf_id") REFERENCES "bcf"("id")
);

CREATE TABLE "clash_manager" (
    "guid1" VARCHAR2(255) NOT NULL,
    "guid2" VARCHAR2(255) NOT NULL,
    "badge" VARCHAR2(50) NOT NULL,
    "entity1" VARCHAR2(255),
    "object1" VARCHAR2(255),
    "entity2" VARCHAR2(255),
    "object2" VARCHAR2(255),
    "x_coord" NUMBER,
    "y_coord" NUMBER,
    "z_coord" NUMBER,
    CONSTRAINT "pk_clash_manager" PRIMARY KEY ("guid1", "guid2")
);

SELECT
  (SELECT COUNT(*) FROM "ifc") AS ifc_total_count,
  (SELECT COUNT(*) FROM "frag") AS frag_total_count,
  (SELECT COUNT(*) FROM "bcf") AS bcf_total_count,
  (SELECT COUNT(*) FROM "ifc_bcf") AS ifc_bcf_total_count,
  (SELECT COUNT(*) FROM "clash_manager") AS clash_manager_total_count
FROM DUAL;

TRUNCATE TABLE "clash_manager";

SELECT "id", "name" FROM "ifc";

SELECT "id", "name" FROM "frag";

DELETE FROM "ifc" WHERE "id" = 162;

DROP TABLE "ifc_bcf";

DROP TABLE "bcf";

DROP TABLE "frag";

DROP TABLE "ifc";

SELECT version, version_full FROM v$instance;

SELECT * FROM v$nls_parameters WHERE parameter LIKE '%CHARACTERSET%';

SHOW CON_NAME;
SHOW PDBS;

ALTER SESSION SET CONTAINER = ORCLPDB;
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;

ALTER SESSION SET CONTAINER = CDB$ROOT;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER mrims IDENTIFIED BY 123456;
DROP USER mrims CASCADE;
GRANT CONNECT, RESOURCE TO mrims;
ALTER USER mrims DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER ifcAdmin IDENTIFIED BY 123456;
GRANT CONNECT, RESOURCE TO ifcAdmin;
GRANT UNLIMITED TABLESPACE TO ifcAdmin;

ALTER PLUGGABLE DATABASE ORCLPDB CLOSE IMMEDIATE;
ALTER PLUGGABLE DATABASE ORCLPDB OPEN READ WRITE;

SELECT username FROM dba_users WHERE username = 'IFCADMIN';
SELECT role FROM dba_roles WHERE role = 'IFCADMIN';
ALTER USER ifcAdmin IDENTIFIED BY 123456 ACCOUNT UNLOCK;

SELECT username, account_status, common
FROM dba_users
WHERE username = 'IFCADMIN';

SELECT name, open_mode, restricted
FROM v$pdbs
WHERE name = 'ORCLPDB';

SELECT status FROM v$instance;
ALTER DATABASE OPEN;
ALTER PLUGGABLE DATABASE ALL SAVE STATE;
SELECT name, open_mode, restricted FROM v$pdbs;
